### ISSUE TITLE
IDC image file meaning is absent in CDA

### ISSUE THREAD

**Issue by ianfore** [CancerDataAggregator/cda-data-model#12]
**Description**
IDC image files are returned in CDA at the top level of organization - the Subject.
IDC files are also not queryable via according to meaningful attributes e.g. "find me the radiographs from the three year follow ups in study X, so I can correlate them with genomic data obtained at surgery in year 0".

**To Reproduce**
See [IDC Pathology notebook](https://github.com/ianfore/cdatest/blob/main/v2tests/IDC%20Pathology.ipynb)
See also [CDA v2 DICOM](https://github.com/ianfore/cdatest/blob/main/v2tests/CDA%20v2%20DICOM.ipynb)

The [CDA v2 DICOM MIDRC](https://github.com/ianfore/cdatest/blob/main/v2tests/CDA%20v2%20DICOM%20MIDRC.ipynb) notebook also explores this issue and shows an example of how the high level structural aspects of the DICOM data model can be used to provide more specific context for image files.

**Expected behavior**
Images should be associated with the appropriate specific object within the Subject.

The underlying issue here is the same as in CancerDataAggregator/cda-data-model#13, however that has a specific focus on pathology, and those specifics should be addressed.

This ticket picks up the bigger issue of the place of images in the overall research-study/treatment protocol.

**Comment by ACharbonneau** [comment]
this was addressed in release 3
