### ISSUE TITLE
derived_from_specimen has mixed semantics. Consider derived_from_biomaterial

### ISSUE THREAD

**Issue by ianfore** [CancerDataAggregator/cda-data-model#7]
See https://github.com/ianfore/cdatest/blob/main/09CO022%20Example.ipynb

The following table shows the specimens for subject 09CO022
  identifier | derived_from_specimen | specimen_type | source_material
 -- | -- | -- | --
4591a53d-5668-4a70-b44b-e08a3d59267e | Initial sample | sample | Primary Tumor
c53c4d60-2ddb-5da8-932e-00a86fa2347f | 4591a53d-5668-4a70-b44b-e08a3d59267e | portion | Primary Tumor
31075cfa-7aef-59f1-bf54-a1cddb5ee0fd | c53c4d60-2ddb-5da8-932e-00a86fa2347f | analyte | Primary Tumor
0d8adcbf-13f0-48c3-83df-3fa205b79ae8 | 31075cfa-7aef-59f1-bf54-a1cddb5ee0fd | aliquot | Primary Tumor
d085ebd9-7605-54a0-abb9-10867f5fa1b1 | 4591a53d-5668-4a70-b44b-e08a3d59267e | portion | Primary Tumor
a31724b6-e550-552b-bd61-41341c534e28 | d085ebd9-7605-54a0-abb9-10867f5fa1b1 | analyte | Primary Tumor
9250d96e-1cdc-4d68-8a56-f7b186a6fab5 | a31724b6-e550-552b-bd61-41341c534e28 | aliquot | Primary Tumor
b12c257d-7409-4858-9384-c430929a075a | Initial sample | sample | Blood Derived Normal
702d7ba0-9558-5b2d-af4d-cd797485b8c1 | b12c257d-7409-4858-9384-c430929a075a | portion | Blood Derived Normal
f0003f0a-07ea-548e-b1f7-7e6d1b27d47a | 702d7ba0-9558-5b2d-af4d-cd797485b8c1 | analyte | Blood Derived Normal
ce309009-9257-4c13-9241-83fc629c35a0 | f0003f0a-07ea-548e-b1f7-7e6d1b27d47a | aliquot | Blood Derived Normal

The designation of the parent specimen as derived from Initial Sample breaks the sample tree. Both are derived from the Subject. (actually from a particular event in the Subject's history). Derived_from_specimen is misleading, it could be read that rows 0 and 7 above derive from the same sample. Derived_from_specimen also has mixed meaning (semantics); in some cases it is a link to the parent object, in others it is a human readable description. A preferable solution would be derived_from_biomaterial where the biomaterial is a specimen or subject as appropriate. This is a common pattern; present in MAGE, FuGE, the Human Cell Atlas, ISA and other standards and systems.

**Comment by kreinold** [comment]
There are two parts to the response:
1. The CDA Data Model follows the CCDH Model with the derived_from_specimen property.  The result must be a specimen; if the specimen is in fact the original specimen taken from the subject, then this property does not exist.  The property derived_from_subject must be a Patient entity and this captures the relationship to the Patient.  Your proposal is another way to achieve this, but I concur with the current approach which more precisely defines the relationship/property.  I wouldn't say that this is breaking the sample tree.

In translating the data model to a BigQuery schema, all entities have the same set of properties.  We have the option of leaving the field empty, using 'null', or using another value to indicate that there is no parent sample.  The approach selected was to include "Initial sample" as the value.  We are happy to indicate that there is no parent sample in another way.  Would you like to suggest something different?

**Comment by kreinold** [comment]
Check in on HCA metadata definition of biomaterial.

**Comment by kreinold** [comment]
Referring part 1 (in comment above) to CCDH.
